import type { Store } from "../core/store.ts";
import { depsOf, type CoreTerm, type Hash } from "../core/term.ts";
import type { Ty } from "../core/types.ts";
import type { Namespace } from "../model.ts";
import { namesOf } from "../project.ts";

function tsType(t: Ty): string {
  switch (t.tag) {
    case "Int":
      return "number";
    case "Bool":
      return "boolean";
    case "Text":
      return "string";
    case "Fun":
      return `(x: ${tsType(t.from)}) => ${tsType(t.to)}`;
  }
}

const TS_OP: Record<string, string> = { "+": "+", "-": "-", "*": "*", "<": "<", ">": ">", "==": "===" };

/** The TS identifier for a hash: its bound name if it has one, else a stable
 *  synthetic name derived from the hash (for anonymous intermediate content). */
function tsName(hash: Hash, nameOf: Map<Hash, string>): string {
  return nameOf.get(hash) ?? "_h" + hash.replace(/[^A-Za-z0-9]/g, "");
}

function emitTerm(t: CoreTerm, nameOf: Map<Hash, string>): string {
  switch (t.tag) {
    case "IntLit":
      return String(t.value);
    case "BoolLit":
      return String(t.value);
    case "TextLit":
      return JSON.stringify(t.value);
    case "Var":
      return t.name;
    case "Ref":
      return tsName(t.hash, nameOf);
    case "App":
      return `${emitTerm(t.fn, nameOf)}(${emitTerm(t.arg, nameOf)})`;
    case "BinOp":
      return `(${emitTerm(t.left, nameOf)} ${TS_OP[t.op]} ${emitTerm(t.right, nameOf)})`;
    case "If":
      return `(${emitTerm(t.cond, nameOf)} ? ${emitTerm(t.then, nameOf)} : ${emitTerm(t.else, nameOf)})`;
  }
}

function emitDef(name: string, hash: Hash, store: Store, nameOf: Map<Hash, string>): string {
  const sd = store.get(hash)!;
  const body = emitTerm(sd.def.body, nameOf);
  if (sd.def.params.length === 0) {
    return `export const ${name}: ${tsType(sd.def.ret)} = ${body};`;
  }
  const ps = sd.def.params;
  let s = `(${ps[ps.length - 1].name}: ${tsType(ps[ps.length - 1].ty)}): ${tsType(sd.def.ret)} => ${body}`;
  for (let i = ps.length - 2; i >= 0; i--) s = `(${ps[i].name}: ${tsType(ps[i].ty)}) => ${s}`;
  return `export const ${name} = ${s};`;
}

/** Transpile a whole namespace to a self-contained TypeScript module. Content
 *  is emitted in dependency order (a definition appears before its users), and
 *  every namespace name resolves to a `const`. This output is both runnable via
 *  the Node/TS toolchain and the faithful human-readable projection of the
 *  content-addressed graph. */
export function emitModule(namespace: Namespace, store: Store): string {
  const nameOf = namesOf(namespace);
  const order: Hash[] = [];
  const seen = new Set<Hash>();
  const visit = (h: Hash): void => {
    if (seen.has(h)) return;
    seen.add(h);
    const sd = store.get(h);
    if (!sd) return;
    for (const d of depsOf(sd.def.body)) visit(d);
    order.push(h);
  };
  for (const [, b] of namespace) visit(b.hash);

  const lines = order.map((h) => emitDef(tsName(h, nameOf), h, store, nameOf));

  // Alias any namespace name that isn't the canonical name chosen for its hash.
  for (const [name, b] of namespace) {
    const canonical = tsName(b.hash, nameOf);
    if (canonical !== name) lines.push(`export const ${name} = ${canonical};`);
  }

  return `// Generated by Strand — transpiled projection of the namespace.\n${lines.join("\n")}\n`;
}
